<a href="https://colab.research.google.com/github/Nidhi-578/DataEngineering/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [90]:
import numpy as np
print("Number of dimensions: ",sales_data.ndim)
print("Shape of sales data: ",sales_data.shape)
print("Total number of values: ",sales_data.size)
print("Data type of the array: ",sales_data.dtype)
print("Memory occuppied by the array: ",sales_data.nbytes)

Number of dimensions:  2
Shape of sales data:  (5, 6)
Total number of values:  30
Data type of the array:  int64
Memory occuppied by the array:  240


Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [91]:
import numpy as np
total_stores=stores.size
total_categories=categories.size
total_store_category_combinations=sales_data.size
print("Total number of stores: ",total_stores)
print("total number of product categories: ",total_categories)
print("Total number of store-category combinations: ",total_store_category_combinations)

Total number of stores:  5
total number of product categories:  6
Total number of store-category combinations:  30


Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [92]:
import numpy as np
sales_float32=sales_data.astype(np.float32)
sales_float64=sales_data.astype(np.float64)

print("sales_data_float32: ",sales_float32.dtype)
print("sales_data_float64: ",sales_float64.dtype)

print("memory used by float32: ",sales_float32.nbytes,"bytes")
print("memory used by float64: ",sales_float64.nbytes,"bytes")


sales_data_float32:  float32
sales_data_float64:  float64
memory used by float32:  120 bytes
memory used by float64:  240 bytes


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [93]:
import numpy as np
bengaluru_sales=sales_data[0]
print("Sales for Bengaluru: ",bengaluru_sales)


Sales for Bengaluru:  [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [94]:
import numpy as np
total_mumbai_store_cost=cost_data[3]
print("Total cost incurred by Mumbai store: ",total_mumbai_store_cost)


Total cost incurred by Mumbai store:  [790000 390000 265000 250000 165000 205000]


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [95]:
import numpy as np
electronics_sales=sales_data[:,0]
print("Electronics sales: ",electronics_sales)

Electronics sales:  [ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [96]:
import numpy as np
clothing_cost=cost_data[:,2]
print("Clothing cost: ",clothing_cost)

Clothing cost:  [220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [97]:
import numpy as np
Furniture_sales=sales_data[1,3]
Furniture_cost=cost_data[1,3]
Furniture_profit=Furniture_sales-Furniture_cost
print("Furniture sales: ",Furniture_sales)
print("Furniture cost: ",Furniture_cost)
print("Furniture profit: ",Furniture_profit)

Furniture sales:  310000
Furniture cost:  225000
Furniture profit:  85000


Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [98]:
import numpy as np
chennai_sales = sales_data[2, 1:4]

print("Chennai Sales (Groceries, Clothing, Furniture):")
print(chennai_sales)

Chennai Sales (Groceries, Clothing, Furniture):
[390000 340000 260000]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [99]:
import numpy as np
store_indices=[0,2,4]
category_indices=[0,2,4]
selected_store_sales=sales_data[store_indices][:,category_indices]
print("Selected Store Sales:")
print(selected_store_sales)

Selected Store Sales:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation

Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [100]:
total_sales_revenue=np.sum(sales_data)
print("Total sales revenue generated by all stores and all categories: ",total_sales_revenue)

Total sales revenue generated by all stores and all categories:  11675000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [101]:
import numpy as np
total_sales_by_store=np.sum(sales_data,axis=1)
for store,sales in zip(stores,total_sales_by_store):
    print(f"{store}: {sales}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [102]:
import numpy as np
total_sales_by_category=np.sum(sales_data,axis=0)
for category,sales in zip(categories,total_sales_by_category):
    print(f"{category}: {sales}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [103]:
import numpy as np
average_sales_per_store=np.mean(sales_data,axis=1)
for store,sales in zip(stores,average_sales_per_store):
    print(f"{store}: {sales:.2f}")


Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.

In [104]:
import numpy as np
average_sales_per_category=np.mean(sales_data,axis=0)
for category,sales in zip(categories,average_sales_per_category):
    print(f"{category}: {sales:.2f}")

Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00


Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [105]:
import numpy as np
highest_selling_store_index=np.argmax(total_sales_by_store)
highest_selling_store=stores[highest_selling_store_index]
highest_selling_store_total_sales=total_sales_by_store[highest_selling_store_index]

print("Index of the store with the highest total sales: ",highest_selling_store_index)
print("Name of the store: ",highest_selling_store)
print("Total sales generated by that store: ",highest_selling_store_total_sales)

Index of the store with the highest total sales:  3
Name of the store:  Mumbai
Total sales generated by that store:  2820000


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

In [106]:
import numpy as np
lowest_selling_store_index=np.argmin(total_sales_by_store)
lowest_selling_store=stores[lowest_selling_store_index]
lowest_selling_store_total_sales=total_sales_by_store[lowest_selling_store_index]

print("Index of the store with the lowest total sales: ",lowest_selling_store_index)
print("Name of the store: ",lowest_selling_store)
print("Total sales generated by that store: ",lowest_selling_store_total_sales)


Index of the store with the lowest total sales:  4
Name of the store:  Pune
Total sales generated by that store:  1980000


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [107]:
import numpy as np
highest_selling_category_index=np.argmax(total_sales_by_category)
highest_selling_category=categories[highest_selling_category_index]
highest_selling_category_total_sales=total_sales_by_category[highest_selling_category_index]
print("Index of the category with the highest total sales: ",highest_selling_category_index)
print("Name of the category: ",highest_selling_category)
print("Total sales generated by that category: ",highest_selling_category_total_sales)


Index of the category with the highest total sales:  0
Name of the category:  Electronics
Total sales generated by that category:  4290000


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [108]:
import numpy as np
lowest_selling_category_index=np.argmin(total_sales_by_category)
lowest_selling_category=categories[lowest_selling_category_index]
lowest_selling_category_total_sales=total_sales_by_category[lowest_selling_category_index]
print("Index of the category with the lowest total sales: ",lowest_selling_category_index)
print("Name of the category: ",lowest_selling_category)
print("Total sales generated by that category: ",lowest_selling_category_total_sales)

Index of the category with the lowest total sales:  4
Name of the category:  Beauty
Total sales generated by that category:  1010000


Part 5: Cost Analysis

Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [109]:
import numpy as np
total_company_cost=np.sum(cost_data)
print("Total cost incurred by SmartMart across all stores and product categories: ",total_company_cost)

Total cost incurred by SmartMart across all stores and product categories:  8600000


In [110]:
Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.

SyntaxError: invalid syntax (2374682564.py, line 1)

In [111]:
import numpy as np
total_cost_by_store=np.sum(cost_data,axis=1)
for store,cost in zip(stores,total_cost_by_store):
    print(f"{store}: {cost:.2f}")

Bengaluru: 1665000.00
Hyderabad: 1685000.00
Chennai: 1710000.00
Mumbai: 2065000.00
Pune: 1475000.00


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [112]:
import numpy as np
total_cost_by_category=np.sum(cost_data,axis=0)
for category,cost in zip(categories,total_cost_by_category):
    print(f"{category}: {cost:.2f}")

Electronics: 3250000.00
Groceries: 1660000.00
Clothing: 1145000.00
Furniture: 1045000.00
Beauty: 665000.00
Sports: 835000.00


Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [113]:
import numpy as np
total_cost_by_store=np.sum(cost_data,axis=1)
most_expensive_store_index=np.argmax(total_cost_by_store)
most_expensive_store=stores[most_expensive_store_index]
most_expensive_store_total_cost=total_cost_by_store[most_expensive_store_index]
print("Index of the store with the highest total operating cost: ",most_expensive_store_index)
print("Name of the store: ",most_expensive_store)
print("Total operating cost of that store: ",most_expensive_store_total_cost)

Index of the store with the highest total operating cost:  3
Name of the store:  Mumbai
Total operating cost of that store:  2065000


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

In [114]:
import numpy as np
lowest_cost_store_index=np.argmin(total_cost_by_store)
lowest_cost_store=stores[lowest_cost_store_index]
lowest_cost_store_total_cost=total_cost_by_store[lowest_cost_store_index]
print("Index of the store with the lowest total operating cost: ",lowest_cost_store_index)
print("Name of the store: ",lowest_cost_store)
print("Total operating cost of that store: ",lowest_cost_store_total_cost)

Index of the store with the lowest total operating cost:  4
Name of the store:  Pune
Total operating cost of that store:  1475000


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [115]:
import numpy as np
most_expensive_category_index=np.argmax(total_cost_by_category)
most_expensive_category=categories[most_expensive_category_index]
most_expensive_category_total_cost=total_cost_by_category[most_expensive_category_index]
print("Index of the category with the highest total operating cost: ",most_expensive_category_index)
print("Name of the category: ",most_expensive_category)
print("Total operating cost of that category: ",most_expensive_category_total_cost)

Index of the category with the highest total operating cost:  0
Name of the category:  Electronics
Total operating cost of that category:  3250000


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [116]:
import numpy as np
profit_data=sales_data-cost_data
print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [117]:
import numpy as np
total_profit_by_store=np.sum(profit_data,axis=1)
for store,profit in zip(stores,total_profit_by_store):
    print(f"{store}: {profit:.2f}")

Bengaluru: 605000.00
Hyderabad: 610000.00
Chennai: 600000.00
Mumbai: 755000.00
Pune: 505000.00


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [118]:
import numpy as np
total_profit_by_category=np.sum(profit_data,axis=0)
for category,profit in zip(categories,total_profit_by_category):
    print(f"{category}: {profit}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [119]:
import numpy as np

total_sales_by_store = np.sum(sales_data, axis=1)
total_cost_by_store = np.sum(cost_data, axis=1)
total_profit_by_store = total_sales_by_store - total_cost_by_store

most_profitable_store_index=np.argmax(total_profit_by_store)

most_profitable_store=stores[most_profitable_store_index]
most_profitable_store_total_sales=total_sales_by_store[most_profitable_store_index]
most_profitable_store_total_cost=total_cost_by_store[most_profitable_store_index]
most_profitable_store_total_profit=total_profit_by_store[most_profitable_store_index]

print("Index of the store with the highest total profit: ",most_profitable_store_index)
print("Name of the store: ",most_profitable_store)
print("Total sales of that store: ",most_profitable_store_total_sales)
print("Total cost of that store: ",most_profitable_store_total_cost)
print("Total profit of that store: ",most_profitable_store_total_profit)

Index of the store with the highest total profit:  3
Name of the store:  Mumbai
Total sales of that store:  2820000
Total cost of that store:  2065000
Total profit of that store:  755000


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [120]:
import numpy as np

total_sales_by_store = np.sum(sales_data, axis=1)
total_cost_by_store = np.sum(cost_data, axis=1)
total_profit_by_store = total_sales_by_store - total_cost_by_store

least_profitable_store_index=np.argmin(total_profit_by_store)

least_profitable_store=stores[least_profitable_store_index]
least_profitable_store_total_sales=total_sales_by_store[least_profitable_store_index]
least_profitable_store_total_cost=total_cost_by_store[least_profitable_store_index]
least_profitable_store_total_profit=total_profit_by_store[least_profitable_store_index]

print("Index of the least profitable store:", least_profitable_store_index)
print("Name of the store:", least_profitable_store)
print("Total sales of that store:", least_profitable_store_total_sales)
print("Total cost of that store:", least_profitable_store_total_cost)
print("Total profit of that store:", least_profitable_store_total_profit)



Index of the least profitable store: 4
Name of the store: Pune
Total sales of that store: 1980000
Total cost of that store: 1475000
Total profit of that store: 505000


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [121]:
import numpy as np

profit_data = sales_data - cost_data
total_profit_by_category = np.sum(profit_data, axis=0)

most_profitable_category_index = np.argmax(total_profit_by_category)
most_profitable_category = categories[most_profitable_category_index]
most_profitable_category_total_profit = total_profit_by_category[most_profitable_category_index]

print("Index of the most profitable category:", most_profitable_category_index)
print("Name of the category:", most_profitable_category)
print("Total profit generated by that category:", most_profitable_category_total_profit)

Index of the most profitable category: 0
Name of the category: Electronics
Total profit generated by that category: 1040000


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [122]:
import numpy as np
profit_data = sales_data - cost_data
total_profit_by_category = np.sum(profit_data, axis=0)
least_profitable_category_index = np.argmin(total_profit_by_category)
least_profitable_category = categories[least_profitable_category_index]
least_profitable_category_total_profit = total_profit_by_category[least_profitable_category_index]
print("Index of the least profitable category:", least_profitable_category_index)
print("Name of the category:", least_profitable_category)
print("Total profit generated by that category:", least_profitable_category_total_profit)

Index of the least profitable category: 5
Name of the category: Sports
Total profit generated by that category: 340000


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [123]:
import numpy as np

profit_data = sales_data - cost_data
maximum_profit = np.max(profit_data)
row_index, column_index = np.unravel_index(np.argmax(profit_data),profit_data.shape)
store_name = stores[row_index]
category_name = categories[column_index]

print("Maximum Profit:", maximum_profit)
print("Store:", store_name)
print("Category:", category_name)

Maximum Profit: 260000
Store: Mumbai
Category: Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [124]:
import numpy as np
profit_data = sales_data - cost_data
minimum_profit = np.min(profit_data)

row_index, column_index = np.unravel_index(
    np.argmin(profit_data),
    profit_data.shape
)

store_name = stores[row_index]
category_name = categories[column_index]

print("Minimum Profit:", minimum_profit)
print("Store:", store_name)
print("Category:", category_name)

Minimum Profit: 55000
Store: Pune
Category: Furniture


Part 7: Profit Margin Analysis

In [125]:
import numpy as np
profit_data = sales_data - cost_data
profit_margin = np.round((profit_data / sales_data) * 100, 2)

print("Profit Margin Matrix (%):")
print(profit_margin)

Profit Margin Matrix (%):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

In [126]:
import numpy as np
total_sales_by_store = np.sum(sales_data, axis=1)
total_cost_by_store = np.sum(cost_data, axis=1)
total_profit_by_store = total_sales_by_store - total_cost_by_store
store_profit_margin = (total_profit_by_store / total_sales_by_store) * 100
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin:.2f}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [127]:
import numpy as np
total_sales_by_category = np.sum(sales_data, axis=0)
total_cost_by_category = np.sum(cost_data, axis=0)
total_profit_by_category = total_sales_by_category - total_cost_by_category
category_profit_margin = (total_profit_by_category / total_sales_by_category) * 100
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin:.2f}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [128]:
import numpy as np
total_sales_by_store = np.sum(sales_data, axis=1)
total_cost_by_store = np.sum(cost_data, axis=1)
total_profit_by_store = total_sales_by_store - total_cost_by_store
store_profit_margin = (total_profit_by_store / total_sales_by_store) * 100
best_store_index = np.argmax(store_profit_margin)

best_store = stores[best_store_index]
best_store_profit_margin = store_profit_margin[best_store_index]

print("Index of Best Store:", best_store_index)
print("Best Store:", best_store)
print("Highest Profit Margin: {:.2f}%".format(best_store_profit_margin))

Index of Best Store: 3
Best Store: Mumbai
Highest Profit Margin: 26.77%


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [129]:
import numpy as np
total_sales_by_category = np.sum(sales_data, axis=0)
total_cost_by_category = np.sum(cost_data, axis=0)
total_profit_by_category = total_sales_by_category - total_cost_by_category
category_profit_margin = (total_profit_by_category / total_sales_by_category) * 100

best_category_index = np.argmax(category_profit_margin)

best_category = categories[best_category_index]
best_category_profit_margin = category_profit_margin[best_category_index]

print("Index of Best Category:", best_category_index)
print("Best Category:", best_category)
print("Highest Profit Margin: {:.2f}%".format(best_category_profit_margin))

Index of Best Category: 4
Best Category: Beauty
Highest Profit Margin: 34.16%


Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [130]:
import numpy as np
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
low_margin = profit_margin < 22

print("Store\t\tCategory\tSales\tCost\tProfit\tProfit Margin")

for row, col in zip(*np.where(low_margin)):
    print(
        stores[row], "\t",
        categories[col], "\t",
        sales_data[row, col], "\t",
        cost_data[row, col], "\t",
        profit_data[row, col], "\t",
        round(profit_margin[row, col], 2), "%"
    )

Store		Category	Sales	Cost	Profit	Profit Margin


Part 8: Boolean Filtering

Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [131]:
import numpy as np
high_sales_values = sales_data[sales_data > 500000]
print("Sales values greater than ₹5,00,000:")
print(high_sales_values)

Sales values greater than ₹5,00,000:
[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

In [132]:
import numpy as np
low_sales_values = sales_data[sales_data < 200000]
print("Sales values less than ₹2,00,000:")
print(low_sales_values)

Sales values less than ₹2,00,000:
[190000 185000 175000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [133]:
import numpy as np
profit_data = sales_data - cost_data
high_profit_values = profit_data[profit_data > 150000]
print("Store-Category combinations with profit greater than ₹1,50,000:")

Store-Category combinations with profit greater than ₹1,50,000:


Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [134]:
import numpy as np
moderate_sales_values = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print("Sales values between ₹2,50,000 and ₹5,00,000:")
print(moderate_sales_values)

Sales values between ₹2,50,000 and ₹5,00,000:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [135]:
import numpy as np
profit_data = sales_data - cost_data
premium_performance = (sales_data > 500000) & (profit_data > 150000)

print("Premium Performing Store-Category Combinations:")
for row, col in zip(*np.where(premium_performance)):
    print("Store:\t", stores[row])
    print("Category:", categories[col])
    print("Sales:\t", sales_data[row, col])
    print("Profit:\t", profit_data[row, col])
    print()


Premium Performing Store-Category Combinations:
Store:	 Bengaluru
Category: Electronics
Sales:	 850000
Profit:	 210000

Store:	 Hyderabad
Category: Electronics
Sales:	 780000
Profit:	 190000

Store:	 Chennai
Category: Electronics
Sales:	 920000
Profit:	 220000

Store:	 Mumbai
Category: Electronics
Sales:	 1050000
Profit:	 260000

Store:	 Pune
Category: Electronics
Sales:	 690000
Profit:	 160000



Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [136]:
import numpy as np
profit_margin = (sales_data - cost_data) / sales_data * 100
underperforming_combinations = (sales_data < 250000) & (profit_margin < 25)

print("Underperforming Store-Category Combinations:")
for row, col in zip(*np.where(underperforming_combinations)):
    print("Store:\t", stores[row])
    print("Category:", categories[col])
    print("Sales:\t", sales_data[row, col])
    print("Profit Margin: {:.2f}%".format(profit_margin[row, col]))
    print()

Underperforming Store-Category Combinations:
Store:	 Pune
Category: Furniture
Sales:	 225000
Profit Margin: 24.44%



Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [137]:
import numpy as np
category_performance = np.where(sales_data >= 500000,"High",np.where(sales_data >= 250000, "Medium", "Low"))

print("Category Performance Classification:")
print(category_performance)

Category Performance Classification:
[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

sales_targets = np.array([ 800000, # Electronics 450000, # Groceries 320000, # Clothing 300000, # Furniture 200000, # Beauty 230000 # Sports ])

Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [141]:
import numpy as np
sales_targets = np.array([800000,450000,320000,300000,200000,230000])

target_comparison = sales_data >= sales_targets

print("Target Comparison:")
print(target_comparison)

Target Comparison:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [143]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])

target_achievement = sales_data >= sales_targets

print("Target Achievement Matrix:")
print(target_achievement)

Target Achievement Matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [144]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=1)
for store, count in zip(stores, achievement_count):
    print(f"{store}: {count}")

Bengaluru: 1
Hyderabad: 4
Chennai: 2
Mumbai: 6
Pune: 0


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [145]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=1)
best_store_index = np.argmax(achievement_count)
best_store = stores[best_store_index]
targets_achieved=achievement_count[best_store_index]

print("Index of Best Store:", best_store_index)
print("Best Performing Store:", best_store)
print("Number of Targets Achieved:", targets_achieved)


Index of Best Store: 3
Best Performing Store: Mumbai
Number of Targets Achieved: 6


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [146]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=0)
for category, count in zip(categories, achievement_count):
    print(f"{category}: {count}")

Electronics: 3
Groceries: 2
Clothing: 2
Furniture: 2
Beauty: 2
Sports: 2


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [147]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
sales_variance = sales_data - sales_targets
for store, variance in zip(stores, sales_variance):
    print(f"{store}: {variance}")

Bengaluru: [ 50000 -30000 -10000 -25000 -10000  -5000]
Hyderabad: [-20000  10000 -25000  10000  10000  10000]
Chennai: [120000 -60000  20000 -40000 -15000 -15000]
Mumbai: [250000  60000  55000  45000  50000  60000]
Pune: [-110000  -45000  -40000  -75000  -25000  -25000]


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [154]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
percentage_variance =np.round((sales_data - sales_targets) / sales_targets * 100)
for store, variance in zip(stores, percentage_variance):
    print(f"{store}: {variance:}")

Bengaluru: [ 6. -7. -3. -8. -5. -2.]
Hyderabad: [-2.  2. -8.  3.  5.  4.]
Chennai: [ 15. -13.   6. -13.  -8.  -7.]
Mumbai: [31. 13. 17. 15. 25. 26.]
Pune: [-14. -10. -12. -25. -12. -11.]


Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [155]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
stores_missing_electronics_target = np.where(target_achievement[:, 0] == False)
for store_index in stores_missing_electronics_target[0]:
    print(stores[store_index])

Hyderabad
Pune


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [156]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
stores_achieving_all_targets = np.all(target_achievement, axis=1)
for store, achieved in zip(stores, stores_achieving_all_targets):
    print(f"{store}: {achieved}")

Bengaluru: False
Hyderabad: False
Chennai: False
Mumbai: True
Pune: False


Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

In [157]:
import numpy as np
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 230000])
target_achievement = sales_data >= sales_targets
stores_achieving_at_least_one_target = np.any(target_achievement, axis=1)
for store, achieved in zip(stores, stores_achieving_at_least_one_target):
    print(f"{store}: {achieved}")

Bengaluru: True
Hyderabad: True
Chennai: True
Mumbai: True
Pune: False


Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [158]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
print("Discount Amount Matrix:")
print(discount_amount)

Discount Amount Matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [159]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
net_sales = sales_data - discount_amount
print("Net Sales Matrix:")
print(net_sales)

Net Sales Matrix:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [160]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
new_profit = sales_data - cost_data - discount_amount
print("New Profit Matrix:")
print(new_profit)

New Profit Matrix:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [161]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
new_profit = sales_data - cost_data - discount_amount
new_profit_margin = (new_profit / sales_data) * 100
print("New Profit Margin Matrix (%):")
print(new_profit_margin)

New Profit Margin Matrix (%):
[[14.70588235 20.         14.03225806 13.45454545 26.21052632 18.88888889]
 [14.35897436 18.91304348 13.81355932 15.41935484 25.33333333 19.16666667]
 [13.91304348 19.35897436 12.94117647 13.         27.13513514 17.90697674]
 [14.76190476 18.52941176 14.33333333 15.53623188 26.         19.31034483]
 [13.1884058  18.45679012 11.78571429 12.44444444 26.28571429 19.26829268]]


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [163]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
new_profit = sales_data - cost_data - discount_amount
loss_making_transactions = new_profit < 0
print("Loss-Making Transactions:")
for row, col in zip(*np.where(loss_making_transactions)):
    print("Store:", stores[row])
    print("Category:", categories[col])
    print()

Loss-Making Transactions:


Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [164]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
total_loss = np.sum(discount_amount)
print("Total Loss due to Discounts: ₹", total_loss)

Total Loss due to Discounts: ₹ 1146350.0


Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

In [166]:
import numpy as np
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
total_discount_by_store = np.sum(discount_amount, axis=1)
store_index = np.argmax(total_discount_by_store)

print("Store Most Affected by Discounts:")
print("Store:", stores[store_index])
print("Total Discount:", total_discount_by_store[store_index])

Store Most Affected by Discounts:
Store: Mumbai
Total Discount: 277150.0


Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [167]:
import numpy as np
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
print("Tax Collection Matrix:")
print(tax_collection)

Tax Collection Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

In [168]:
import numpy as np
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
sales_including_tax = sales_data + tax_collection
print("Sales Including Tax Matrix:")
print(sales_including_tax)

Sales Including Tax Matrix:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [169]:
import numpy as np
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
total_tax_by_store = np.sum(tax_collection, axis=1)
for store, tax in zip(stores, total_tax_by_store):
    print(f"{store}: {tax}")

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

In [170]:
import numpy as np
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
total_tax_by_category = np.sum(tax_collection, axis=0)
for category, tax in zip(categories, total_tax_by_category):
    print(f"{category}: {tax}")

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [171]:
import numpy as np
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
total_tax_by_store = np.sum(tax_collection, axis=1)
highest_tax_store_index = np.argmax(total_tax_by_store)
highest_tax_store = stores[highest_tax_store_index]
highest_tax_amount = total_tax_by_store[highest_tax_store_index]
print("Highest Tax-Contributing Store:")
print("Store:", highest_tax_store)
print("Total Tax Amount:", highest_tax_amount)

Highest Tax-Contributing Store:
Store: Mumbai
Total Tax Amount: 401400.0


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [174]:
import numpy as np
updated_sales_data = sales_data.copy()
updated_sales_data[4, 0] = 740000

print("Original Pune Electronics Sales:", sales_data[4, 0])
print("Updated Pune Electronics Sales:", updated_sales_data[4, 0])

Original Pune Electronics Sales: 690000
Updated Pune Electronics Sales: 740000


Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [175]:
import numpy as np
updated_cost_data = cost_data.copy()
updated_cost_data[:, 4] = updated_cost_data[:, 4] * 0.92

print("Original Beauty Cost:")
print(cost_data[:, 4])

print("Updated Beauty Cost:")
print(updated_cost_data[:, 4])

Original Beauty Cost:
[125000 140000 120000 165000 115000]
Updated Beauty Cost:
[115000 128800 110400 151800 105800]


Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [176]:
import numpy as np
updated_cost_data = cost_data.copy()
updated_cost_data[:, 3] = updated_cost_data[:, 3] * 1.12

print("Original Furniture Cost:")
print(cost_data[:, 3])

print("Updated Furniture Cost:")
print(updated_cost_data[:, 3])

Original Furniture Cost:
[205000 225000 195000 250000 170000]
Updated Furniture Cost:
[229600 252000 218400 280000 190400]


Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [177]:
import numpy as np
updated_sales_data = np.delete(sales_data, 4, axis=0)
updated_cost_data = np.delete(cost_data, 4, axis=0)
print("Updated Sales Data:")
print(updated_sales_data)
print("Updated Cost Data:")
print(updated_cost_data)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
Updated Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [178]:
import numpy as np
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])
updated_sales_data = np.vstack((sales_data, delhi_sales))
updated_cost_data = np.vstack((cost_data, delhi_cost))
stores = np.append(stores, "Delhi")
print("Updated Sales Data:")
print(updated_sales_data)
print("Updated Cost Data:")
print(updated_cost_data)
print("Updated Stores Array:")
print(stores)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Updated Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
Updated Stores Array:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().

In [179]:
import numpy as np
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])
updated_sales_data = np.column_stack((sales_data, home_appliance_sales))
updated_cost_data = np.column_stack((cost_data, home_appliance_cost))
categories = np.append(categories, "Home Appliances")
print("Updated Sales Data:")
print(updated_sales_data)
print("Updated Cost Data:")
print(updated_cost_data)
print("Updated Categories Array:")
print(categories)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Updated Cost Data:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
Updated Categories Array:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


Part 13: Sorting and Ranking

Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [180]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
sorted_indices = np.argsort(total_sales)
sorted_stores = stores[sorted_indices]
sorted_sales = total_sales[sorted_indices]
for store, sales in zip(sorted_stores, sorted_sales):
    print(f"{store}: ₹{sales}")


Pune: ₹1980000
Bengaluru: ₹2270000
Hyderabad: ₹2295000
Chennai: ₹2310000
Mumbai: ₹2820000


Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

In [181]:
import numpy as np
profit = sales_data - cost_data
total_profit = np.sum(profit, axis=1)
ranked_indices = np.argsort(total_profit)[::-1]
ranked_stores = stores[ranked_indices]
ranked_profits = total_profit[ranked_indices]
for store, profit in zip(ranked_stores, ranked_profits):
    print(f"{store}: ₹{profit}")


Mumbai: ₹755000
Hyderabad: ₹610000
Bengaluru: ₹605000
Chennai: ₹600000
Pune: ₹505000


Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

In [182]:
import numpy as np
total_revenue = np.sum(sales_data, axis=0)
sorted_indices = np.argsort(total_revenue)[::-1]
sorted_categories = categories[sorted_indices]
sorted_revenues = total_revenue[sorted_indices]
for category, revenue in zip(sorted_categories, sorted_revenues):
    print(f"{category}: ₹{revenue}")

Electronics: ₹4290000
Groceries: ₹2185000
Clothing: ₹1600000
Furniture: ₹1415000
Sports: ₹1175000
Beauty: ₹1010000


Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [183]:
import numpy as np
flattened_sales = sales_data.flatten()
sorted_indices = np.argsort(flattened_sales)[::-1]
top_three_indices = sorted_indices[:3]
top_three_sales = flattened_sales[top_three_indices]
top_three_stores = stores[top_three_indices // sales_data.shape[1]]
top_three_categories = categories[top_three_indices % sales_data.shape[1]]

for sales, store, category in zip(top_three_sales, top_three_stores, top_three_categories):
    print(f"Sales: ₹{sales}, Store: {store}, Category: {category}")

Sales: ₹1050000, Store: Mumbai, Category: Electronics
Sales: ₹920000, Store: Chennai, Category: Electronics
Sales: ₹850000, Store: Bengaluru, Category: Electronics


Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [186]:
import numpy as np
profit = sales_data - cost_data
flattened_profit = profit.flatten()
sorted_indices = np.argsort(flattened_profit)
bottom_three_indices = sorted_indices[:3]
for index in bottom_three_indices:
    store_index = index // profit.shape[1]
    category_index = index % profit.shape[1]
    print(f"Store: {stores[store_index]}, Category: {categories[category_index]}, Profit: ₹{flattened_profit[index]}")

Store: Pune, Category: Furniture, Profit: ₹55000
Store: Pune, Category: Sports, Profit: ₹60000
Store: Chennai, Category: Sports, Profit: ₹60000


Part 14: Statistical Analysis

Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [187]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_dev_sales = np.std(sales_data)
var_sales = np.var(sales_data)
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)
print("Sales Statistics:")
print("Minimum Sales:", min_sales)
print("Maximum Sales:", max_sales)
print("Mean Sales:", mean_sales)
print("Median Sales:", median_sales)
print("Standard Deviation of Sales:", std_dev_sales)
print("Variance of Sales:", var_sales)
print("25th Percentile of Sales:", percentile_25)
print("50th Percentile of Sales:", percentile_50)
print("75th Percentile of Sales:", percentile_75)

Sales Statistics:
Minimum Sales: 175000
Maximum Sales: 1050000
Mean Sales: 389166.6666666667
Median Sales: 302500.0
Standard Deviation of Sales: 230322.53954448793
Variance of Sales: 53048472222.222206
25th Percentile of Sales: 228750.0
50th Percentile of Sales: 302500.0
75th Percentile of Sales: 416250.0


Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [188]:
import numpy as np
std_dev_by_store = np.std(sales_data, axis=1)
max_std_dev_store_index = np.argmax(std_dev_by_store)
max_std_dev_store = stores[max_std_dev_store_index]
print("Store with the Most Variation:")
print("Store:", max_std_dev_store)
print("Standard Deviation:", std_dev_by_store[max_std_dev_store_index])


Store with the Most Variation:
Store: Mumbai
Standard Deviation: 271860.871280391


Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

In [189]:
import numpy as np
std_dev_by_category = np.std(sales_data, axis=0)
max_std_dev_category_index = np.argmax(std_dev_by_category)
max_std_dev_category = categories[max_std_dev_category_index]
print("Category with the Highest Variation:")
print("Category:", max_std_dev_category)
print("Standard Deviation:", std_dev_by_category[max_std_dev_category_index])


Category with the Highest Variation:
Category: Electronics
Standard Deviation: 122539.78945632312


Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [190]:
import numpy as np
company_average_sales = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_average_sales)
print("Company-Wide Average Sales:", company_average_sales)
print("Number of Store-Category Sales Above Average:", above_average_count)


Company-Wide Average Sales: 389166.6666666667
Number of Store-Category Sales Above Average: 10


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [191]:
import numpy as np
threshold = np.mean(sales_data) + 1.5 * np.std(sales_data)
outliers = sales_data[sales_data > threshold]
print("High-Value Outliers:")
print(outliers)

High-Value Outliers:
[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [192]:
import numpy as np
sales_flatten = sales_data.flatten()
sales_ravel = sales_data.ravel()

print("Using flatten():")
print(sales_flatten)

print("Using ravel():")
print(sales_ravel)

Using flatten():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Using ravel():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [193]:
import numpy as np

sales_3x10 = sales_data.reshape(3, 10)
sales_10x3 = sales_data.reshape(10, 3)
sales_2x15 = sales_data.reshape(2, 15)
sales_15x2 = sales_data.reshape(15, 2)

print("3 x 10:")
print(sales_3x10)
print("\n10 x 3:")
print(sales_10x3)
print("\n2 x 15:")
print(sales_2x15)
print("\n15 x 2:")
print(sales_15x2)
print("Original Elements:", sales_data.size)
print("3 x 10 Elements:", sales_3x10.size)
print("10 x 3 Elements:", sales_10x3.size)
print("2 x 15 Elements:", sales_2x15.size)
print("15 x 2 Elements:", sales_15x2.size)


3 x 10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10 x 3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2 x 15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15 x 2:
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  51000

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

In [195]:
import numpy as np
transposed_sales = np.transpose(sales_data)
print("Transposed Sales Data:")
print(transposed_sales)
print("New Shape:", transposed_sales.shape)

Transposed Sales Data:
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New Shape: (6, 5)


Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

In [196]:
import numpy as np
combined_data = np.vstack((sales_data, cost_data))
print("Combined Sales and Cost Data:")
print(combined_data)
print("New Shape:", combined_data.shape)

Combined Sales and Cost Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
New Shape: (10, 6)


Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [197]:
import numpy as np
combined_data = np.stack((sales_data, cost_data), axis=0)
print("Combined Sales and Cost Data:")
print(combined_data)
print("New Shape:", combined_data.shape)

Combined Sales and Cost Data:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
New Shape: (2, 5, 6)


Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [201]:
import numpy as np
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

missing_values = np.isnan(sales_with_missing)
total_missing = np.sum(missing_values)
rows, cols = np.where(missing_values)

print("Total Missing Values:", total_missing)

print("Location of Missing Values:")
for row, col in zip(rows, cols):
    print(f"Row: {row}, Column: {col}")

print("Stores and Categories Containing Missing Values:")
for row, col in zip(rows, cols):
    print(f"Store: {stores[row]}, Category: {categories[col]}")


Total Missing Values: 4
Location of Missing Values:
Row: 0, Column: 2
Row: 1, Column: 3
Row: 3, Column: 1
Row: 4, Column: 4
Stores and Categories Containing Missing Values:
Store: Bengaluru, Category: Clothing
Store: Hyderabad, Category: Furniture
Store: Mumbai, Category: Groceries
Store: Pune, Category: Beauty


Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [202]:
import numpy as np
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

missing_values = np.isnan(sales_with_missing)
total_missing = np.sum(missing_values)
rows, cols = np.where(missing_values)

print("Total Missing Values:", total_missing)

print("Location of Missing Values:")
for row, col in zip(rows, cols):
    print(f"Row: {row}, Column: {col}")

print("Stores and Categories Containing Missing Values:")
for row, col in zip(rows, cols):
    print(f"Store: {stores[row]}, Category: {categories[col]}")


Total Missing Values: 4
Location of Missing Values:
Row: 0, Column: 2
Row: 1, Column: 3
Row: 3, Column: 1
Row: 4, Column: 4
Stores and Categories Containing Missing Values:
Store: Bengaluru, Category: Clothing
Store: Hyderabad, Category: Furniture
Store: Mumbai, Category: Groceries
Store: Pune, Category: Beauty


Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

In [203]:
import numpy as np

sales_no_missing = np.nan_to_num(sales_with_missing, nan=0)

print("Sales Data After Replacing Missing Values with 0:")
print(sales_no_missing)


Sales Data After Replacing Missing Values with 0:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [206]:
import numpy as np
company_average = np.nanmean(sales_with_missing)
updated_sales = sales_with_missing.copy()
updated_sales[np.isnan(updated_sales)] = company_average

print("Company Average Sales:", company_average)

print("\nSales Data After Replacing Missing Values:")
print(updated_sales)

Company Average Sales: 398846.1538461539

Sales Data After Replacing Missing Values:
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [207]:
import numpy as np
updated_sales = sales_with_missing.copy()
for i in range(updated_sales.shape[0]):
    for j in range(updated_sales.shape[1]):
        if np.isnan(updated_sales[i, j]):
            category_sales = sales_with_missing[:, j]
            category_sales = category_sales[~np.isnan(category_sales)]
            if len(category_sales) > 0:
                updated_sales[i, j] = np.mean(category_sales)

print("Sales Data After Replacing Missing Values with Category Averages:")
print(updated_sales)


Sales Data After Replacing Missing Values with Category Averages:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

In [208]:
import numpy as np
total_sales_before = np.nansum(sales_with_missing)
sales_zero = np.nan_to_num(sales_with_missing, nan=0)
total_sales_after = np.sum(sales_zero)

print("Total Sales Before Replacing Missing Values:", total_sales_before)
print("Total Sales After Replacing Missing Values with Zero:", total_sales_after)
print("Difference:", total_sales_after - total_sales_before)


Total Sales Before Replacing Missing Values: 10370000.0
Total Sales After Replacing Missing Values with Zero: 10370000.0
Difference: 0.0


Part 17: Conditional Business Decisions

Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [213]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
conditions = [total_sales > 2800000,(total_sales >= 2400000) & (total_sales <= 2800000),total_sales < 2400000]

labels = ["Excellent", "Good", "Needs Improvement"]

store_labels = np.select(conditions, labels, default="Unknown")

for store, sales, label in zip(stores, total_sales, store_labels):
    print(f"{store}: Total Sales = ₹{sales}, Label = {label}")


Bengaluru: Total Sales = ₹2270000, Label = Needs Improvement
Hyderabad: Total Sales = ₹2295000, Label = Needs Improvement
Chennai: Total Sales = ₹2310000, Label = Needs Improvement
Mumbai: Total Sales = ₹2820000, Label = Excellent
Pune: Total Sales = ₹1980000, Label = Needs Improvement


Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [217]:
import numpy as np
profit = sales_data - cost_data
conditions = [
    profit > 200000,
    (profit >= 100000) & (profit <= 200000),
    (profit >= 0) & (profit < 100000),
    profit < 0
]

labels = [
    "Highly Profitable",
    "Profitable",
    "Low Profit",
    "Loss"
]

profit_labels = np.select(conditions, labels, default="Unknown")

for i in range(profit.shape[0]):
    for j in range(profit.shape[1]):
        print(f"{stores[i]} - {categories[j]}: {profit_labels[i, j]}")

Bengaluru - Electronics: Highly Profitable
Bengaluru - Groceries: Profitable
Bengaluru - Clothing: Low Profit
Bengaluru - Furniture: Low Profit
Bengaluru - Beauty: Low Profit
Bengaluru - Sports: Low Profit
Hyderabad - Electronics: Profitable
Hyderabad - Groceries: Profitable
Hyderabad - Clothing: Low Profit
Hyderabad - Furniture: Low Profit
Hyderabad - Beauty: Low Profit
Hyderabad - Sports: Low Profit
Chennai - Electronics: Highly Profitable
Chennai - Groceries: Low Profit
Chennai - Clothing: Low Profit
Chennai - Furniture: Low Profit
Chennai - Beauty: Low Profit
Chennai - Sports: Low Profit
Mumbai - Electronics: Highly Profitable
Mumbai - Groceries: Profitable
Mumbai - Clothing: Profitable
Mumbai - Furniture: Low Profit
Mumbai - Beauty: Low Profit
Mumbai - Sports: Low Profit
Pune - Electronics: Profitable
Pune - Groceries: Low Profit
Pune - Clothing: Low Profit
Pune - Furniture: Low Profit
Pune - Beauty: Low Profit
Pune - Sports: Low Profit


Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [218]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_profit = np.sum(profit, axis=1)
overall_profit_margin = (total_profit / total_sales) * 100


eligible_stores = np.where(
    (total_sales > 2500000) &
    (total_profit > 700000) &
    (overall_profit_margin > 25)
)[0]

print("Eligible Stores for Expansion:")

for store_index in eligible_stores:
    print(stores[store_index])

Eligible Stores for Expansion:
Mumbai


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [219]:
import numpy as np
average_sales = np.mean(sales_data, axis=0)
total_sales = np.sum(sales_data, axis=0)
profit = sales_data - cost_data
total_profit = np.sum(profit, axis=0)
profit_margin = (total_profit / total_sales) * 100
promotion_categories = np.where(
    (average_sales < 300000) &
    (profit_margin > 25)
)[0]

print("Categories Recommended for Promotion:")

for index in promotion_categories:
    print(f"Category: {categories[index]}")
    print(f"Average Sales: ₹{average_sales[index]:.0f}")
    print(f"Profit Margin: {profit_margin[index]:.2f}%")
    print()

Categories Recommended for Promotion:
Category: Furniture
Average Sales: ₹283000
Profit Margin: 26.15%

Category: Beauty
Average Sales: ₹202000
Profit Margin: 34.16%

Category: Sports
Average Sales: ₹235000
Profit Margin: 28.94%



Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [221]:
import numpy as np
profit = sales_data - cost_data
profit_margin = (profit / sales_data) * 100
rows, cols = np.where(
    (cost_data > 250000) &
    (profit_margin < 25)
)

print("Store-Category Combinations Recommended for Cost Optimization:")

for row, col in zip(rows, cols):
    print(f"Store: {stores[row]}")
    print(f"Category: {categories[col]}")
    print(f"Cost: ₹{cost_data[row, col]}")
    print(f"Profit Margin: {profit_margin[row, col]:.2f}%")
    print()

Store-Category Combinations Recommended for Cost Optimization:
Store: Bengaluru
Category: Electronics
Cost: ₹640000
Profit Margin: 24.71%

Store: Hyderabad
Category: Electronics
Cost: ₹590000
Profit Margin: 24.36%

Store: Hyderabad
Category: Groceries
Cost: ₹350000
Profit Margin: 23.91%

Store: Chennai
Category: Electronics
Cost: ₹700000
Profit Margin: 23.91%

Store: Chennai
Category: Groceries
Cost: ₹295000
Profit Margin: 24.36%

Store: Mumbai
Category: Electronics
Cost: ₹790000
Profit Margin: 24.76%

Store: Mumbai
Category: Groceries
Cost: ₹390000
Profit Margin: 23.53%

Store: Pune
Category: Electronics
Cost: ₹530000
Profit Margin: 23.19%

Store: Pune
Category: Groceries
Cost: ₹310000
Profit Margin: 23.46%



In [223]:
#Part 18: Inventory Scenario
#Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [224]:
import numpy as np
closing_stock = opening_stock - units_sold
print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units

In [226]:
import numpy as np
low_stock_indices = np.where(closing_stock < 30)
low_stock_stores = [stores[i] for i in low_stock_indices[0]]
low_stock_categories = [categories[j] for j in low_stock_indices[1]]
print("Store-Category Combinations with Low Stock:")
for store, category in zip(low_stock_stores, low_stock_categories):
    print(f"Store: {store}, Category: {category}")
    print()

Store-Category Combinations with Low Stock:
Store: Bengaluru, Category: Electronics

Store: Bengaluru, Category: Furniture

Store: Hyderabad, Category: Electronics

Store: Hyderabad, Category: Furniture

Store: Chennai, Category: Electronics

Store: Chennai, Category: Furniture

Store: Mumbai, Category: Electronics

Store: Pune, Category: Electronics

Store: Pune, Category: Furniture



Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [227]:
import numpy as np
unsold_percentage = (np.sum(opening_stock - units_sold) / np.sum(opening_stock)) * 100
print(f"Percentage of Opening Stock Unsold: {unsold_percentage:.2f}%")


Percentage of Opening Stock Unsold: 19.66%


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [228]:
import numpy as np
stock_sold_percentage = ((opening_stock - closing_stock) / opening_stock) * 100
rows, cols = np.where(stock_sold_percentage > 80)
print("Fast-Moving Store-Category Combinations:")
for row, col in zip(rows, cols):
    print(f"Store: {stores[row]}")
    print(f"Category: {categories[col]}")
    print(f"Opening Stock: {opening_stock[row, col]}")
    print(f"Closing Stock: {closing_stock[row, col]}")
    print(f"Stock Sold: {stock_sold_percentage[row, col]:.2f}%")
    print()

Fast-Moving Store-Category Combinations:
Store: Bengaluru
Category: Groceries
Opening Stock: 450
Closing Stock: 70
Stock Sold: 84.44%

Store: Hyderabad
Category: Groceries
Opening Stock: 500
Closing Stock: 80
Stock Sold: 84.00%

Store: Hyderabad
Category: Clothing
Opening Stock: 280
Closing Stock: 50
Stock Sold: 82.14%

Store: Chennai
Category: Electronics
Opening Stock: 130
Closing Stock: 25
Stock Sold: 80.77%

Store: Chennai
Category: Groceries
Opening Stock: 420
Closing Stock: 70
Stock Sold: 83.33%

Store: Chennai
Category: Clothing
Opening Stock: 320
Closing Stock: 50
Stock Sold: 84.38%

Store: Mumbai
Category: Electronics
Opening Stock: 150
Closing Stock: 25
Stock Sold: 83.33%

Store: Mumbai
Category: Groceries
Opening Stock: 550
Closing Stock: 80
Stock Sold: 85.45%

Store: Mumbai
Category: Clothing
Opening Stock: 350
Closing Stock: 55
Stock Sold: 84.29%

Store: Pune
Category: Groceries
Opening Stock: 400
Closing Stock: 70
Stock Sold: 82.50%



Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [230]:
import numpy as np
units_sold = opening_stock - closing_stock
category_units_sold = np.sum(units_sold, axis=0)

print("Category-Wise Units Sold:")

for category, units in zip(categories, category_units_sold):
    print(f"{category}: {units} units")

Category-Wise Units Sold:
Electronics: 485 units
Groceries: 1950 units
Clothing: 1240 units
Furniture: 345 units
Beauty: 980 units
Sports: 720 units


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [231]:
import numpy as np
units_sold = opening_stock - closing_stock
store_units_sold = np.sum(units_sold, axis=1)
print("Store-Wise Units Sold:")
for store, units in zip(stores, store_units_sold):
    print(f"{store}: {units} units")

Store-Wise Units Sold:
Bengaluru: 1110 units
Hyderabad: 1175 units
Chennai: 1095 units
Mumbai: 1390 units
Pune: 950 units


Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [232]:
import numpy as np
units_sold = opening_stock - closing_stock
store_units_sold = np.sum(units_sold, axis=1)
best_store_index = np.argmax(store_units_sold)

print("Best Store by Unit Sales:")
print("Store:", stores[best_store_index])
print("Total Units Sold:", store_units_sold[best_store_index])

Best Store by Unit Sales:
Store: Mumbai
Total Units Sold: 1390


Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [233]:
import numpy as np
reorder_matrix = closing_stock < 25
print("Reorder Requirement Matrix:")
print(reorder_matrix)

Reorder Requirement Matrix:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [234]:
import numpy as np
reorder_quantity = np.where(closing_stock < 25,100 - closing_stock,0)
print("Reorder Quantity Matrix:")
print(reorder_quantity)

Reorder Quantity Matrix:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [235]:
import numpy as np
cumulative_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Store Sales:")
for store, sales in zip(stores, cumulative_sales):
    print(store, ":", sales)

Cumulative Store Sales:
Bengaluru : [ 850000 1270000 1580000 1855000 2045000 2270000]
Hyderabad : [ 780000 1240000 1535000 1845000 2055000 2295000]
Chennai : [ 920000 1310000 1650000 1910000 2095000 2310000]
Mumbai : [1050000 1560000 1935000 2280000 2530000 2820000]
Pune : [ 690000 1095000 1375000 1600000 1775000 1980000]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [236]:
import numpy as np
flat_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flat_sales)

print("Flattened Sales Data:")
print(flat_sales)

print("\nCumulative Company Sales:")
print(cumulative_company_sales)

Flattened Sales Data:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

In [237]:
import numpy as np
sales_difference = np.diff(sales_data, axis=1)
print("Difference Between Consecutive Category Sales:")

for store, difference in zip(stores, sales_difference):
    print(f"{store}: {difference}")

Difference Between Consecutive Category Sales:
Bengaluru: [-430000 -110000  -35000  -85000   35000]
Hyderabad: [-320000 -165000   15000 -100000   30000]
Chennai: [-530000  -50000  -80000  -75000   30000]
Mumbai: [-540000 -135000  -30000  -95000   40000]
Pune: [-285000 -125000  -55000  -50000   30000]


Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.

In [238]:
import numpy as np
unique_sales, counts = np.unique(sales_data, return_counts=True)
print("Unique Sales Values and Their Frequencies:")

for sale, count in zip(unique_sales, counts):
    print(f"Sales: ₹{sale}, Frequency: {count}")

Unique Sales Values and Their Frequencies:
Sales: ₹175000, Frequency: 1
Sales: ₹185000, Frequency: 1
Sales: ₹190000, Frequency: 1
Sales: ₹205000, Frequency: 1
Sales: ₹210000, Frequency: 1
Sales: ₹215000, Frequency: 1
Sales: ₹225000, Frequency: 2
Sales: ₹240000, Frequency: 1
Sales: ₹250000, Frequency: 1
Sales: ₹260000, Frequency: 1
Sales: ₹275000, Frequency: 1
Sales: ₹280000, Frequency: 1
Sales: ₹290000, Frequency: 1
Sales: ₹295000, Frequency: 1
Sales: ₹310000, Frequency: 2
Sales: ₹340000, Frequency: 1
Sales: ₹345000, Frequency: 1
Sales: ₹375000, Frequency: 1
Sales: ₹390000, Frequency: 1
Sales: ₹405000, Frequency: 1
Sales: ₹420000, Frequency: 1
Sales: ₹460000, Frequency: 1
Sales: ₹510000, Frequency: 1
Sales: ₹690000, Frequency: 1
Sales: ₹780000, Frequency: 1
Sales: ₹850000, Frequency: 1
Sales: ₹920000, Frequency: 1
Sales: ₹1050000, Frequency: 1


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [240]:
import numpy as np
search_value = 420000
rows, cols = np.where(sales_data == search_value)
if len(rows) > 0:
    print(f"{search_value} exists in the sales data")

    for row, col in zip(rows, cols):
        print(f"Store: {stores[row]}")
        print(f"Category: {categories[col]}")
        print(f"Location: Row {row}, Column {col}")
else:
    print(f"{search_value} does not exist in the sales data")

420000 exists in the sales data
Store: Bengaluru
Category: Groceries
Location: Row 0, Column 1


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [241]:
import numpy as np
sales_greater_than_cost = sales_data > cost_data

print("Sales Greater Than Cost Matrix:")
print(sales_greater_than_cost)
all_profitable = np.all(sales_greater_than_cost)

print("Are all store-category combinations profitable?")
print(all_profitable)

Sales Greater Than Cost Matrix:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
Are all store-category combinations profitable?
True


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [242]:
import numpy as np
profit = sales_data - cost_data
reporting_profit = np.clip(profit, 75000, 250000)

print("Reporting Profit Array:")
print(reporting_profit)

Reporting Profit Array:
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [243]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("Normalized Sales Data:")
print(normalized_sales)

Normalized Sales Data:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [244]:
import numpy as np
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print("Standardized Sales Data:")
print(standardized_sales)

Standardized Sales Data:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [245]:
import numpy as np
profit = sales_data - cost_data
profit_margin = (profit / sales_data) * 100
two_decimal = np.round(profit_margin, 2)
whole_number = np.round(profit_margin)
floor_values = np.floor(profit_margin)
ceiling_values = np.ceil(profit_margin)
print("Profit Margin (2 Decimal Places):")
print(two_decimal)
print("Profit Margin (Nearest Whole Number):")
print(whole_number)
print("Profit Margin (Floor Values):")
print(floor_values)
print("Profit Margin (Ceiling Values):")
print(ceiling_values)

Profit Margin (2 Decimal Places):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Profit Margin (Nearest Whole Number):
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Profit Margin (Floor Values):
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Profit Margin (Ceiling Values):
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [246]:
import numpy as np
profit_data = sales_data - cost_data
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")
print("Sales Data Equal:", np.array_equal(sales_data, loaded_sales))
print("Cost Data Equal:", np.array_equal(cost_data, loaded_cost))
print("Profit Data Equal:", np.array_equal(profit_data, loaded_profit))

Sales Data Equal: True
Cost Data Equal: True
Profit Data Equal: True


Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder
Expected Final Output Format
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity: